### ISSUE TITLE
progress_bar=True , error : AttributeError

### ISSUE THREAD

**Issue by mousavand** [CiwPython/Ciw#178]
job_number = 1000
Q.simulate_until_max_customers(job_number, progress_bar=True, method='Arrive')

When I debug the program, following error prompts :

Exception has occurred: AttributeError
module 'sys' has no attribute 'setcheckinterval'

**Comment by mousavand** [comment]
1.

**Comment by geraintpalmer** [comment]
I can't reproduce this error.

What Ciw version are you using?

**Comment by mousavand** [comment]
Requirement already satisfied: ciw in c:\python\python39\lib\site-packages **(2.1.3)**
Requirement already satisfied: PyYAML>=5.1 in c:\python\python39\lib\site-packages (from ciw) (5.3.1)
Requirement already satisfied: networkx>=2.3 in c:\python\python39\lib\site-packages (from ciw) (2.5)
Requirement already satisfied: tqdm==4.14.0 in c:\python\python39\lib\site-packages (from ciw) (4.14.0)
Requirement already satisfied: decorator>=4.3.0 in c:\python\python39\lib\site-packages (from networkx>=2.3->ciw) (4.4.2)

**Comment by geraintpalmer** [comment]
Thank you @mousavand 

It looks like this feature doesn't work with Python 3.9.

Ciw is supported for Python versions 3.5, 3.6, 3.7 and 3.8, and so works on these versions.

I'm not sure what the problem is with Python 3.9 yet, but I'll investigate and hopefully address this soon.
